###Get all Movies
GET localhost:8080/api/v1/movie
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwidXNlcm5hbWUiOiJ0YXdrZW5zaXkwIiwic3ViIjoidGF3a2Vuc2l5MCIsImlhdCI6MTcyOTQwNDE2NSwiZXhwIjoxNzI5NDkwNTY1fQ.7VnFFBs5cDpVwSW5m9wpeb_AvjZqjuucY1BaVyow9Xg5Ef95KrE3fa66ruWWNtWkMrwe4EMhu4BYQU_yXwo_Qg

###Get Movie By id
GET localhost:8080/api/v1/movie/1

###Create Movie
POST localhost:8080/api/v1/movie
Content-Type: application/json

{
  "title": "nma gap",
  "description": "solal"
}

###Create Movie with Genres
POST localhost:8080/api/v1/movie
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwidXNlcm5hbWUiOiJ0YXdrZW5zaXkwIiwic3ViIjoidGF3a2Vuc2l5MCIsImlhdCI6MTcyOTQwNDE2NSwiZXhwIjoxNzI5NDkwNTY1fQ.7VnFFBs5cDpVwSW5m9wpeb_AvjZqjuucY1BaVyow9Xg5Ef95KrE3fa66ruWWNtWkMrwe4EMhu4BYQU_yXwo_Qg

  {
        "title": "Osmondagi Bolalar",
        "description": "Bolala xaqida",
        "genres": [
            {
                "name": "Fantastika"
            }
        ]
    }

###Update Movie
PUT localhost:8080/api/v1/profile/1
Content-Type: application/json

  {
        "title": "ozgardi",
        "description": "ozgardi",
        "genres": [
            {
                "name": "1 ikki"
            }
        ]
    }

